//
//  Names.swift
//  BabyNames
//
//  Created by Tyler Lafferty on 7/25/18.
//  Copyright © 2018 Tyler Lafferty. All rights reserved.
//

import UIKit
import Foundation

enum Gender: String {
    case male = "male"
    case female = "female"
    case either = "either"
}

enum Origin: String {
    case english = "English"
    case italian = "Italian"
    case french = "French"
}

class Name: NSObject, NSCoding {
    var name: String
    var meaning: String
    var origin: Origin
    var gender: Gender
    
    init(name: String, meaning: String, origin: Origin, gender: Gender) {
        self.name = name
        self.meaning = meaning
        self.origin = origin
        self.gender = gender
    }
    
    required convenience init(coder aDecoder : NSCoder) {
        let name = aDecoder.decodeObject(forKey: "name") as! String
        let meaning = aDecoder.decodeObject(forKey: "meaning") as! String
        let origin = Origin(rawValue: aDecoder.decodeObject(forKey: "origin") as! String)
        let gender = Gender(rawValue: aDecoder.decodeObject(forKey: "gender") as! String)
        self.init(name: name, meaning: meaning, origin: origin!, gender: gender!)
    }
    
    func encode(with aCoder: NSCoder) {
        aCoder.encode(name, forKey: "name")
        aCoder.encode(meaning, forKey: "meaning")
        aCoder.encode(origin.rawValue, forKey: "origin")
        aCoder.encode(gender.rawValue, forKey: "gender")
    }
}

var FEMALE_NAMES: [Name] = [
    Name(name: "Abbey", meaning: "Varient of Abigail", origin: .english, gender: .female),
    Name(name: "Abbie", meaning: "Varient of Abigail", origin: .english, gender: .female),
    Name(name: "Abigail", meaning: "Biblical name meaning 'father of exaltation", origin: .english, gender: .female),
    Name(name: "Ada", meaning: "Pet forms of the girl’s names Adele or Adelaide", origin: .english, gender: .female),
    Name(name: "Adelaide", meaning: "English form of the French name Adélaïde", origin: .english, gender: .female),
    Name(name: "Adele", meaning: "English form of the French name Adéle", origin: .english, gender: .female),
    Name(name: "Adrienne", meaning: "Feminine of the name Adrian", origin: .english, gender: .female),
    Name(name: "Agatha", meaning: "Good or honourable from agathos", origin: .english, gender: .female),
    Name(name: "Agnes", meaning: "Pure, or holy from the word hagnos", origin: .english, gender: .female),
    Name(name: "Aileen", meaning: "Variant of the girl’s name Eileen", origin: .english, gender: .female),
    Name(name: "Alana", meaning: "Feminine form of Alan", origin: .english, gender: .female),
    Name(name: "Alex", meaning: "Variant of the name Alexandra or Alexis", origin: .english, gender: .female),
    Name(name: "Alexandra", meaning: "From the words ‘Defender of Mankind’ and Warrior", origin: .english, gender: .female),
    Name(name: "Alice", meaning: "Based on the girl’s name Adelaide", origin: .english, gender: .female),
    Name(name: "Alina", meaning: "From the names Alina and Linda", origin: .english, gender: .female),
    Name(name: "Alison", meaning: "Norman diminutive of Alice", origin: .english, gender: .female),
    Name(name: "Alma", meaning: "River in the Crimea", origin: .english, gender: .female),
    Name(name: "Amanda", meaning: "Means loveable", origin: .english, gender: .female),
    Name(name: "Amber", meaning: "From the gemstone amber", origin: .english, gender: .female),
    Name(name: "Amelia", meaning: "A mix between the names Emilia and Amalia", origin: .english, gender: .female),
    Name(name: "Amy", meaning: "Anglicized from Amee (old French)", origin: .english, gender: .female),
    Name(name: "Andrea", meaning: "Feminine form of the name Andrew", origin: .english, gender: .female),
    Name(name: "Angela", meaning: "This name means Angelic", origin: .english, gender: .female),
    Name(name: "Ann", meaning: "English spelling of Anne", origin: .english, gender: .female),
    Name(name: "Annabelle", meaning: "Likely from Amabel", origin: .english, gender: .female),
    Name(name: "Anne", meaning: "From the Hebrew girl’s name Hanna", origin: .english, gender: .female),
    Name(name: "Anthea", meaning: "From the Greek name Antheia", origin: .english, gender: .female),
    Name(name: "April", meaning: "English form of aprilis. Also a month.", origin: .english, gender: .female),
    Name(name: "Arlene", meaning: "Probably based on Marlene or Charlene", origin: .english, gender: .female),
    Name(name: "Ashley", meaning: "Derived from old English Ash and Wood", origin: .english, gender: .female),
    Name(name: "Audrey", meaning: "From an old English name which means noble strength", origin: .english, gender: .female),
    Name(name: "Ava", meaning: "Was a 9th-century saint St Ava or Avis", origin: .english, gender: .female),
    Name(name: "Avril", meaning: "Taken from April", origin: .english, gender: .female),
    Name(name: "Babs", meaning: "Pet form of the girl’s name Barbara", origin: .english, gender: .female),
    Name(name: "Bailey", meaning: "This is a meaning", origin: .english, gender: .female),
    Name(name: "Barbara", meaning: "Means foreign woman", origin: .english, gender: .female),
    Name(name: "Bea", meaning: "Short form of Beatrix or Beatrice", origin: .english, gender: .female),
    Name(name: "Beatrix", meaning: "Voyager/Blessed", origin: .english, gender: .female),
    Name(name: "Becky", meaning: "From the girl’s name Rebecca", origin: .english, gender: .female),
    Name(name: "Belinda", meaning: "Uncertain origin", origin: .english, gender: .female),
    Name(name: "Bella", meaning: "Short form of Isabella", origin: .english, gender: .female),
    Name(name: "Bernice", meaning: "From Berenice", origin: .english, gender: .female),
    Name(name: "Berry", meaning: "From the fruit", origin: .english, gender: .female),
    Name(name: "Bertha", meaning: "Bright or famous", origin: .english, gender: .female),
    Name(name: "Beryl", meaning: "A gemstone", origin: .english, gender: .female),
    Name(name: "Bess", meaning: "From the English name Elizabeth", origin: .english, gender: .female),
    Name(name: "Bet", meaning: "From the English name Elizabeth", origin: .english, gender: .female),
    Name(name: "Beth", meaning: "From Elizabeth", origin: .english, gender: .female),
    Name(name: "Bethany", meaning: "Village outside Jerusalem", origin: .english, gender: .female),
    Name(name: "Betsy", meaning: "Pet form of Elizabeth", origin: .english, gender: .female),
    Name(name: "Betty", meaning: "From the English girl’s name Elizabeth", origin: .english, gender: .female),
    Name(name: "Beverly", meaning: "From a Beaver Stream/Meadow", origin: .english, gender: .female),
    Name(name: "Blanche", meaning: "Blonde, white or fair", origin: .english, gender: .female),
    Name(name: "Bobbie", meaning: "Variant of the name Roberta", origin: .english, gender: .female),
    Name(name: "Bonnie", meaning: "This English girl’s name mean fine, attractive, lovely", origin: .english, gender: .female),
    Name(name: "Brenda", meaning: "Flaming sword", origin: .english, gender: .female),
    Name(name: "Brianne", meaning: "The feminine of Brian", origin: .english, gender: .female),
    Name(name: "Bridget", meaning: "Anglicized from Brighid", origin: .english, gender: .female),
    Name(name: "Britney", meaning: "From Britain", origin: .english, gender: .female),
    Name(name: "Brittany", meaning: "From Britain", origin: .english, gender: .female),
    Name(name: "Brooke", meaning: "From the Brook", origin: .english, gender: .female),
    Name(name: "Camilla", meaning: "From the old Roman name Camillus", origin: .english, gender: .female),
    Name(name: "Candice", meaning: "From Candace", origin: .english, gender: .female),
    Name(name: "Cara", meaning: "To beloved", origin: .english, gender: .female),
    Name(name: "Carissa", meaning: "Tender Touch", origin: .english, gender: .female),
    Name(name: "Carla", meaning: "Feminine of Charles", origin: .english, gender: .female),
    Name(name: "Carly", meaning: "Pet form of Carla", origin: .english, gender: .female),
    Name(name: "Carmel", meaning: "Christian origins", origin: .english, gender: .female),
    Name(name: "Carol", meaning: "Anglicised form of Carolus", origin: .english, gender: .female),
    Name(name: "Caroline", meaning: "Anglicised form of Carolus", origin: .english, gender: .female),
    Name(name: "Carrie", meaning: "Form of Caroline", origin: .english, gender: .female),
    Name(name: "Cass", meaning: "Short for the girl’s name Cassandra", origin: .english, gender: .female),
    Name(name: "Catherine", meaning: "A variant of the name Katherine", origin: .english, gender: .female),
    Name(name: "Cathy", meaning: "A short form of Catherine", origin: .english, gender: .female),
    Name(name: "Charis", meaning: "From the Greek name haris to grace", origin: .english, gender: .female),
    Name(name: "Charity", meaning: "Affection/’Love for fellow man’", origin: .english, gender: .female),
    Name(name: "Charlene", meaning: "Originates from the name Charles", origin: .english, gender: .female),
    Name(name: "Charlie", meaning: "Pet name for Charles", origin: .english, gender: .female),
    Name(name: "Charlotte", meaning: "From the name Charles", origin: .english, gender: .female),
    Name(name: "Chelsea", meaning: "Means Harbour, and place in London", origin: .english, gender: .female),
    Name(name: "Cherida", meaning: "A mix between Cheryl and Phillida", origin: .english, gender: .female),
    Name(name: "Cherish", meaning: "To treasure", origin: .english, gender: .female),
    Name(name: "Cheryl", meaning: "Origins unknown, possibly from Cherry and Beryl", origin: .english, gender: .female),
    Name(name: "Chloe", meaning: "This name originated from the Greek name khlóē", origin: .english, gender: .female),
    Name(name: "Christina", meaning: "Feminine form of Christian", origin: .english, gender: .female),
    Name(name: "Christine", meaning: "Form of the girl’s name Christina", origin: .english, gender: .female),
    Name(name: "Clara", meaning: "Feminine form of Clarus", origin: .english, gender: .female),
    Name(name: "Clare", meaning: "A form of Clara", origin: .english, gender: .female),
    Name(name: "Clarissa", meaning: "A version of the name Clarice", origin: .english, gender: .female),
    Name(name: "Claudia", meaning: "Originates from the name Claudius", origin: .english, gender: .female),
    Name(name: "Connie", meaning: "Pet form of Constance", origin: .english, gender: .female),
    Name(name: "Courtney", meaning: "Popular in America from the place Courtnay in France", origin: .english, gender: .female),
    Name(name: "Cynthia", meaning: "From the girl’s name Kynthia", origin: .english, gender: .female),
    Name(name: "Daisy", meaning: "The name comes from the flower", origin: .english, gender: .female),
    Name(name: "Darlene", meaning: "From the English word Darling", origin: .english, gender: .female),
    Name(name: "Davida", meaning: "Feminine form of David", origin: .english, gender: .female),
    Name(name: "Dawn", meaning: "Mean in English – day break", origin: .english, gender: .female),
    Name(name: "Deborah", meaning: "Biblical name", origin: .english, gender: .female),
    Name(name: "Dee", meaning: "Pet name of Dorothy", origin: .english, gender: .female),
    Name(name: "Deirdre", meaning: "From Celtic legend Deidre of the Sorrows", origin: .english, gender: .female),
    Name(name: "Delia", meaning: "From the place Delos", origin: .english, gender: .female),
    Name(name: "Dena", meaning: "Possibly from the name Dean", origin: .english, gender: .female),
    Name(name: "Diana", meaning: "Roman goddess of the moon and hunting", origin: .english, gender: .female),
    Name(name: "Dina", meaning: "English variant of Dinah", origin: .english, gender: .female),
    Name(name: "Dolly", meaning: "Pet form of Dorothy", origin: .english, gender: .female),
    Name(name: "Donna", meaning: "From the name Madonna", origin: .english, gender: .female),
    Name(name: "Dora", meaning: "From doron meaning a gift", origin: .english, gender: .female),
    Name(name: "Doreen", meaning: "From the name Dora", origin: .english, gender: .female),
    Name(name: "Doris", meaning: "Of the Sea", origin: .english, gender: .female),
    Name(name: "Dorothy", meaning: "From the English girl’s name Dorothea", origin: .english, gender: .female),
    Name(name: "Ebony", meaning: "English name from black wood", origin: .english, gender: .female),
    Name(name: "Edith", meaning: "From the words for fortune, riches and strife", origin: .english, gender: .female),
    Name(name: "Edna", meaning: "English form of Eithne", origin: .english, gender: .female),
    Name(name: "Edwina", meaning: "Feminine of Edwin", origin: .english, gender: .female),
    Name(name: "Effie", meaning: "Pet form of the name Euphemia", origin: .english, gender: .female),
    Name(name: "Elaine", meaning: "A derived from Helen", origin: .english, gender: .female),
    Name(name: "Eleanor", meaning: "A derived from Helen", origin: .english, gender: .female),
    Name(name: "Elena", meaning: "Form of Helen", origin: .english, gender: .female),
    Name(name: "Elinor", meaning: "Variation of Eleanor", origin: .english, gender: .female),
    Name(name: "Eliza", meaning: "Short form of Elizabeth", origin: .english, gender: .female),
    Name(name: "Elizabeth", meaning: "Made popular by Queen Elizabeth I", origin: .english, gender: .female),
    Name(name: "Ella", meaning: "A variant of the name Ellen", origin: .english, gender: .female),
    Name(name: "Ellen", meaning: "Form of Helen", origin: .english, gender: .female),
    Name(name: "Ellie", meaning: "Pet form of Eleanor/Ellen/Helen", origin: .english, gender: .female),
    Name(name: "Elsa", meaning: "Short form of Elizabeth", origin: .english, gender: .female),
    Name(name: "Emily", meaning: "Feminine version of the name Aemilius", origin: .english, gender: .female),
    Name(name: "Emma", meaning: "From the names Ermintrude and Irmgard", origin: .english, gender: .female),
    Name(name: "Emmy", meaning: "Pet form of Emma or Emily", origin: .english, gender: .female),
    Name(name: "Enola", meaning: "Origins unknown", origin: .english, gender: .female),
    Name(name: "Erin", meaning: "Angliszed name from Eirinn", origin: .english, gender: .female),
    Name(name: "Esta", meaning: "Version of Esther", origin: .english, gender: .female),
    Name(name: "Estelle", meaning: "Means star", origin: .english, gender: .female),
    Name(name: "Ethel", meaning: "Means noble", origin: .english, gender: .female),
    Name(name: "Eudora", meaning: "Good Gift", origin: .english, gender: .female),
    Name(name: "Eugenia", meaning: "From the name Eugenios", origin: .english, gender: .female),
    Name(name: "Eunice", meaning: "Good victory", origin: .english, gender: .female),
    Name(name: "Eve", meaning: "A biblical name", origin: .english, gender: .female),
    Name(name: "Evelyn", meaning: "Comes from the girl’s name Aveline", origin: .english, gender: .female),
    Name(name: "Evette", meaning: "Form of Yvette", origin: .english, gender: .female),
    Name(name: "Evie", meaning: "Pet form of Eve or Eva", origin: .english, gender: .female),
    Name(name: "Evonne", meaning: "English Girl’s name based on Yvonne", origin: .english, gender: .female),
    Name(name: "Faith", meaning: "Faith and belief in God", origin: .english, gender: .female),
    Name(name: "Fanny", meaning: "Pet form of Frances", origin: .english, gender: .female),
    Name(name: "Fay", meaning: "Half sister of King Arthur", origin: .english, gender: .female),
    Name(name: "Faye", meaning: "Half sister of King Arthur", origin: .english, gender: .female),
    Name(name: "Felicity", meaning: "Means good luck", origin: .english, gender: .female),
    Name(name: "Fern", meaning: "Means fern plant", origin: .english, gender: .female),
    Name(name: "Flo", meaning: "Comes from the verb to work", origin: .english, gender: .female),
    Name(name: "Flora", meaning: "Goddess of flowers", origin: .english, gender: .female),
    Name(name: "Florence", meaning: "From the name Florentius", origin: .english, gender: .female),
    Name(name: "Florrie", meaning: "Pet name for Flora", origin: .english, gender: .female),
    Name(name: "Fran", meaning: "Short for Frances", origin: .english, gender: .female),
    Name(name: "Frances", meaning: "Female version of Francis", origin: .english, gender: .female),
    Name(name: "Freda", meaning: "Short name Winfred or Elfreda", origin: .english, gender: .female),
    Name(name: "Gail", meaning: "From Abigail", origin: .english, gender: .female),
    Name(name: "Gale", meaning: "From Abigail", origin: .english, gender: .female),
    Name(name: "Gayle", meaning: "From Abigail", origin: .english, gender: .female),
    Name(name: "Gaynor", meaning: "From Guinevere", origin: .english, gender: .female),
    Name(name: "Georgia", meaning: "Feminine of George", origin: .english, gender: .female),
    Name(name: "Georgiana", meaning: "Feminine of George", origin: .english, gender: .female),
    Name(name: "Geraldine", meaning: "Female form of Gerald", origin: .english, gender: .female),
    Name(name: "Germaine", meaning: "From Germanus", origin: .english, gender: .female),
    Name(name: "Gertrude", meaning: "From the words ‘gar’ (spear) and ‘prup’ (strength)", origin: .english, gender: .female),
    Name(name: "Gill", meaning: "Pet form of Gillian", origin: .english, gender: .female),
    Name(name: "Gillian", meaning: "Feminine of Julian", origin: .english, gender: .female),
    Name(name: "Gloria", meaning: "From glorious", origin: .english, gender: .female),
    Name(name: "Glynis", meaning: "From Glenys", origin: .english, gender: .female),
    Name(name: "Grace", meaning: "From the name Gratia", origin: .english, gender: .female),
    Name(name: "Gracie", meaning: "Pet form of the English name Grace", origin: .english, gender: .female),
    Name(name: "Gretta", meaning: "English version of the name Greta", origin: .english, gender: .female),
    Name(name: "Guinevere", meaning: "English girl’s name from Gwenhwfar", origin: .english, gender: .female),
    Name(name: "Haley", meaning: "Version of Hayley", origin: .english, gender: .female),
    Name(name: "Harriet", meaning: "English version of the name Henriette", origin: .english, gender: .female),
    Name(name: "Hattie", meaning: "From Harriet", origin: .english, gender: .female),
    Name(name: "Hayley", meaning: "Place in Oxfordshire", origin: .english, gender: .female),
    Name(name: "Hazel", meaning: "From the nuts", origin: .english, gender: .female),
    Name(name: "Heather", meaning: "From the heather plant", origin: .english, gender: .female),
    Name(name: "Helen", meaning: "English version of the Greek name Helene", origin: .english, gender: .female),
    Name(name: "Henrietta", meaning: "Female version of Henri", origin: .english, gender: .female),
    Name(name: "Hettie", meaning: "Pet form of Henrietta", origin: .english, gender: .female),
    Name(name: "Hilary", meaning: "From the name Hilarius", origin: .english, gender: .female),
    Name(name: "Hilda", meaning: "Means to battle", origin: .english, gender: .female),
    Name(name: "Hollie", meaning: "Alternative spelling of the name Holly", origin: .english, gender: .female),
    Name(name: "Holly", meaning: "The name comes from the holly bush", origin: .english, gender: .female),
    Name(name: "Honey", meaning: "From honey that bees produce", origin: .english, gender: .female),
    Name(name: "Hope", meaning: "From the word meaning hope", origin: .english, gender: .female),
    Name(name: "Hyacinth", meaning: "From mythology", origin: .english, gender: .female),
    Name(name: "Ida", meaning: "Comes from the verb to work", origin: .english, gender: .female),
    Name(name: "Imogen", meaning: "From Shakespeare", origin: .english, gender: .female),
    Name(name: "Iole", meaning: "From mythology", origin: .english, gender: .female),
    Name(name: "Irene", meaning: "The name means peace", origin: .english, gender: .female),
    Name(name: "Iris", meaning: "This English name means rainbow", origin: .english, gender: .female),
    Name(name: "Isabel", meaning: "From the Spanish version of Elizabeth", origin: .english, gender: .female),
    Name(name: "Isabella", meaning: "From Isabel", origin: .english, gender: .female),
    Name(name: "Isabelle", meaning: "From the name Isabel", origin: .english, gender: .female),
    Name(name: "Ivy", meaning: "From the plant Ivy", origin: .english, gender: .female),
    Name(name: "Jackie", meaning: "From Jacqueline", origin: .english, gender: .female),
    Name(name: "Jacqueline", meaning: "Feminine of Jacques", origin: .english, gender: .female),
    Name(name: "Jade", meaning: "From a gemstone", origin: .english, gender: .female),
    Name(name: "Jane", meaning: "Female name for John", origin: .english, gender: .female),
    Name(name: "Janet", meaning: "From the name Jane", origin: .english, gender: .female),
    Name(name: "Janette", meaning: "From the name Jane", origin: .english, gender: .female),
    Name(name: "Janice", meaning: "Mix between Jan and Frances", origin: .english, gender: .female),
    Name(name: "Jasmine", meaning: "From a flower", origin: .english, gender: .female),
    Name(name: "Jay", meaning: "Pet form of Kay or Dee", origin: .english, gender: .female),
    Name(name: "Jean", meaning: "From the name Jeanne", origin: .english, gender: .female),
    Name(name: "Jeane", meaning: "Form of Jean", origin: .english, gender: .female),
    Name(name: "Jennet", meaning: "English spelling of Jeannette", origin: .english, gender: .female),
    Name(name: "Jennifer", meaning: "From the name Guinevere", origin: .english, gender: .female),
    Name(name: "Jenny", meaning: "From the English girl’s name Jennifer", origin: .english, gender: .female),
    Name(name: "Jess", meaning: "Pet form of Jessica", origin: .english, gender: .female),
    Name(name: "Jessica", meaning: "From Shakespeare", origin: .english, gender: .female),
    Name(name: "Jessie", meaning: "Pet form of Jean", origin: .english, gender: .female),
    Name(name: "Jewel", meaning: "From the gemstone", origin: .english, gender: .female),
    Name(name: "Jill", meaning: "From Gillian", origin: .english, gender: .female),
    Name(name: "Joan", meaning: "From the name Joanna", origin: .english, gender: .female),
    Name(name: "Jodie", meaning: "Uncertain origin", origin: .english, gender: .female),
    Name(name: "Josephine", meaning: "The analgised version of the French name", origin: .english, gender: .female),
    Name(name: "Joy", meaning: "Meaning delight", origin: .english, gender: .female),
    Name(name: "Joyce", meaning: "From the name Josce", origin: .english, gender: .female),
    Name(name: "Judy", meaning: "From the name Judith", origin: .english, gender: .female),
    Name(name: "Juliet", meaning: "English version of the name Juliette", origin: .english, gender: .female),
    Name(name: "June", meaning: "From the month of the year", origin: .english, gender: .female),
    Name(name: "Justine", meaning: "Female version of the name Justin", origin: .english, gender: .female),
    Name(name: "Kaley", meaning: "From the name Kayley", origin: .english, gender: .female),
    Name(name: "Kate", meaning: "From the name Katherine", origin: .english, gender: .female),
    Name(name: "Katherine", meaning: "From the saint", origin: .english, gender: .female),
    Name(name: "Katie", meaning: "From the name Kate (and therefore Katherine)", origin: .english, gender: .female),
    Name(name: "Katy", meaning: "From Katie", origin: .english, gender: .female),
    Name(name: "Kay", meaning: "Short form of Katherine", origin: .english, gender: .female),
    Name(name: "Kayla", meaning: "Variants of Kay", origin: .english, gender: .female),
    Name(name: "Kayley", meaning: "Means slender", origin: .english, gender: .female),
    Name(name: "Keeley", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Kelly", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Kendra", meaning: "From Kendrick", origin: .english, gender: .female),
    Name(name: "Kerena", meaning: "From the name Keren", origin: .english, gender: .female),
    Name(name: "Kerry", meaning: "From the Irish county", origin: .english, gender: .female),
    Name(name: "Kim", meaning: "From the girl’s name Kimberley", origin: .english, gender: .female),
    Name(name: "Kimberley", meaning: "From the place in South Africa", origin: .english, gender: .female),
    Name(name: "Kitty", meaning: "From the name Katherine", origin: .english, gender: .female),
    Name(name: "Kyla", meaning: "From Kyle", origin: .english, gender: .female),
    Name(name: "Kyle", meaning: "Means narrow channel", origin: .english, gender: .female),
    Name(name: "Kylie", meaning: "Mean boomerang", origin: .english, gender: .female),
    Name(name: "Lacey", meaning: "From the surname", origin: .english, gender: .female),
    Name(name: "Lana", meaning: "Uncertain origin", origin: .english, gender: .female),
    Name(name: "Laura", meaning: "From the name Laurus", origin: .english, gender: .female),
    Name(name: "Lauren", meaning: "From the name Laurence", origin: .english, gender: .female),
    Name(name: "Leanne", meaning: "From the names Lee & Anne", origin: .english, gender: .female),
    Name(name: "Lee", meaning: "Clearing", origin: .english, gender: .female),
    Name(name: "Lena", meaning: "From names ending in lena or lina like Helena", origin: .english, gender: .female),
    Name(name: "Leona", meaning: "From the name Leon", origin: .english, gender: .female),
    Name(name: "Lesley", meaning: "From Leslie", origin: .english, gender: .female),
    Name(name: "Lexi", meaning: "From Alexandra", origin: .english, gender: .female),
    Name(name: "Lexy", meaning: "From Alexandra (see Lexi for more information)", origin: .english, gender: .female),
    Name(name: "Libby", meaning: "From the English name Elizabeth", origin: .english, gender: .female),
    Name(name: "Lilian", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Lilly", meaning: "From the flower", origin: .english, gender: .female),
    Name(name: "Lily", meaning: "From the flower", origin: .english, gender: .female),
    Name(name: "Linda", meaning: "From the name Belinda", origin: .english, gender: .female),
    Name(name: "Linda", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Lindsay", meaning: "The name originates from the place Lincoln", origin: .english, gender: .female),
    Name(name: "Lindy", meaning: "From the name Linda", origin: .english, gender: .female),
    Name(name: "Linette", meaning: "A variant of the name Linnette", origin: .english, gender: .female),
    Name(name: "Liona", meaning: "From the name Leona", origin: .english, gender: .female),
    Name(name: "Lisa", meaning: "From the French name Lise", origin: .english, gender: .female),
    Name(name: "Livia", meaning: "From Olivia", origin: .english, gender: .female),
    Name(name: "Liz", meaning: "From the name Elizabeth", origin: .english, gender: .female),
    Name(name: "Liza", meaning: "From the name Elizabeth", origin: .english, gender: .female),
    Name(name: "Lizzie", meaning: "From the name Elizabeth", origin: .english, gender: .female),
    Name(name: "Lola", meaning: "From Dolores", origin: .english, gender: .female),
    Name(name: "Loretta", meaning: "English version of Lauretta", origin: .english, gender: .female),
    Name(name: "Lorraine", meaning: "A place name Lorraine in France", origin: .english, gender: .female),
    Name(name: "Lottie", meaning: "From the girl’s name Charlotte", origin: .english, gender: .female),
    Name(name: "Louise", meaning: "Female version of Louis", origin: .english, gender: .female),
    Name(name: "Lucy", meaning: "From the old French name Lucie", origin: .english, gender: .female),
    Name(name: "Lynette", meaning: "From the name Lynn", origin: .english, gender: .female),
    Name(name: "Lynn", meaning: "From the girl’s name Linda", origin: .english, gender: .female),
    Name(name: "Mabel", meaning: "The name means lovely", origin: .english, gender: .female),
    Name(name: "Madeline", meaning: "A biblical name", origin: .english, gender: .female),
    Name(name: "Madge", meaning: "From the English name Margaret", origin: .english, gender: .female),
    Name(name: "Madonna", meaning: "From biblical name My Lady", origin: .english, gender: .female),
    Name(name: "Maggie", meaning: "From the name Margaret", origin: .english, gender: .female),
    Name(name: "Maggie", meaning: "Pet form of Margaret", origin: .english, gender: .female),
    Name(name: "Malvina", meaning: "A fictitious name", origin: .english, gender: .female),
    Name(name: "Mandy", meaning: "From Amanda", origin: .english, gender: .female),
    Name(name: "Mara", meaning: "A English name with biblical origins", origin: .english, gender: .female),
    Name(name: "Marcia", meaning: "Feminine form of Mark", origin: .english, gender: .female),
    Name(name: "Margaret", meaning: "From the French name Marguerite", origin: .english, gender: .female),
    Name(name: "Marice", meaning: "English version og Maris", origin: .english, gender: .female),
    Name(name: "Marilyn", meaning: "Originates from the name Mary", origin: .english, gender: .female),
    Name(name: "Mary", meaning: "English girl’s name from Marie or Maria", origin: .english, gender: .female),
    Name(name: "Maud", meaning: "From the name Matilda", origin: .english, gender: .female),
    Name(name: "Maura", meaning: "From St Maura", origin: .english, gender: .female),
    Name(name: "Maureen", meaning: "From the Irish name Mairin", origin: .english, gender: .female),
    Name(name: "Mavis", meaning: "Means song thrush", origin: .english, gender: .female),
    Name(name: "Maxine", meaning: "Feminine version of the name Max", origin: .english, gender: .female),
    Name(name: "May", meaning: "Pet name for Mary and Margaret", origin: .english, gender: .female),
    Name(name: "Maya", meaning: "Influenced by May", origin: .english, gender: .female),
    Name(name: "Meg", meaning: "Pet form of Margaret", origin: .english, gender: .female),
    Name(name: "Melanie", meaning: "From Melania (dark haired)", origin: .english, gender: .female),
    Name(name: "Melinda", meaning: "A name derived from Melanie and Lucinda", origin: .english, gender: .female),
    Name(name: "Melissa", meaning: "This name means bee", origin: .english, gender: .female),
    Name(name: "Melody", meaning: "From the melody of a song", origin: .english, gender: .female),
    Name(name: "Mercy", meaning: "Compassionate or forgiveness", origin: .english, gender: .female),
    Name(name: "Merle", meaning: "Girl’s name from Meriel", origin: .english, gender: .female),
    Name(name: "Mildred", meaning: "Means gentle and strong", origin: .english, gender: .female),
    Name(name: "Millicent", meaning: "From the words meaning labour and strength", origin: .english, gender: .female),
    Name(name: "Millie", meaning: "Pet form of Amelia, Camilla, Melissa", origin: .english, gender: .female),
    Name(name: "Minnie", meaning: "From the name Wilhelmina", origin: .english, gender: .female),
    Name(name: "Mirabelle", meaning: "Mean wondrous beauty or love", origin: .english, gender: .female),
    Name(name: "Miranda", meaning: "From Shakespeare", origin: .english, gender: .female),
    Name(name: "Misty", meaning: "From the word mist/fog", origin: .english, gender: .female),
    Name(name: "Molly", meaning: "Version of the girl’s name Mary", origin: .english, gender: .female),
    Name(name: "Mona", meaning: "From the name Muadhnait meaning noble", origin: .english, gender: .female),
    Name(name: "Monica", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Muriel", meaning: "From the Celtic name Muireall", origin: .english, gender: .female),
    Name(name: "Myra", meaning: "Created by a poet in 17th century", origin: .english, gender: .female),
    Name(name: "Myrtle", meaning: "From the plant", origin: .english, gender: .female),
    Name(name: "Nadia", meaning: "English version of the name Nadezhda", origin: .english, gender: .female),
    Name(name: "Nancy", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Nell", meaning: "Pet form of Eleanor/Ellen/Helen", origin: .english, gender: .female),
    Name(name: "Nerissa", meaning: "From Shakespeare", origin: .english, gender: .female),
    Name(name: "Nessa", meaning: "From Agnessa", origin: .english, gender: .female),
    Name(name: "Nicola", meaning: "From the name Nicholas", origin: .english, gender: .female),
    Name(name: "Nita", meaning: "Pet form of Anita", origin: .english, gender: .female),
    Name(name: "Nora", meaning: "Pet form of names like Eleanor", origin: .english, gender: .female),
    Name(name: "Noreen", meaning: "From the Gaelic name Noirin", origin: .english, gender: .female),
    Name(name: "Norma", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Octavia", meaning: "Meaning eighth", origin: .english, gender: .female),
    Name(name: "Olive", meaning: "From the olive plant", origin: .english, gender: .female),
    Name(name: "Olivia", meaning: "From Shakespeare", origin: .english, gender: .female),
    Name(name: "Opal", meaning: "From the gemstone", origin: .english, gender: .female),
    Name(name: "Pamela", meaning: "Created by a poet Philip Sidney", origin: .english, gender: .female),
    Name(name: "Pandora", meaning: "From mythology", origin: .english, gender: .female),
    Name(name: "Pansy", meaning: "From the flower", origin: .english, gender: .female),
    Name(name: "Patience", meaning: "Means virtuous", origin: .english, gender: .female),
    Name(name: "Patricia", meaning: "Feminine version of Patrick", origin: .english, gender: .female),
    Name(name: "Patsy", meaning: "Pet form of Patricia", origin: .english, gender: .female),
    Name(name: "Paula", meaning: "Form of Paul", origin: .english, gender: .female),
    Name(name: "Pearl", meaning: "From the gemstone", origin: .english, gender: .female),
    Name(name: "Peggy", meaning: "From Maggie", origin: .english, gender: .female),
    Name(name: "Penelope", meaning: "From mythology", origin: .english, gender: .female),
    Name(name: "Petra", meaning: "Female version of Peter", origin: .english, gender: .female),
    Name(name: "Petula", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Philippa", meaning: "From the name Philip", origin: .english, gender: .female),
    Name(name: "Philomena", meaning: "From a saint", origin: .english, gender: .female),
    Name(name: "Phoebe", meaning: "From the moon goddess", origin: .english, gender: .female),
    Name(name: "Phyllis", meaning: "From mythology", origin: .english, gender: .female),
    Name(name: "Pippa", meaning: "From the English girl’s name Philippa", origin: .english, gender: .female),
    Name(name: "Polly", meaning: "Variant of Molly", origin: .english, gender: .female),
    Name(name: "Poppy", meaning: "From the name of the flower", origin: .english, gender: .female),
    Name(name: "Primrose", meaning: "From the flower", origin: .english, gender: .female),
    Name(name: "Prudence", meaning: "From the verb prudent", origin: .english, gender: .female),
    Name(name: "Prunella", meaning: "Plum colour", origin: .english, gender: .female),
    Name(name: "Queenie", meaning: "Name for the Queen", origin: .english, gender: .female),
    Name(name: "Rachel", meaning: "A biblical name", origin: .english, gender: .female),
    Name(name: "Raine", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Reanna", meaning: "From Deanna", origin: .english, gender: .female),
    Name(name: "Reenie", meaning: "From the name Rene", origin: .english, gender: .female),
    Name(name: "Regina", meaning: "Meaning Queen", origin: .english, gender: .female),
    Name(name: "Rhoda", meaning: "This girl’s name means rose", origin: .english, gender: .female),
    Name(name: "Rikki", meaning: "Girl’s version of the name Ricky", origin: .english, gender: .female),
    Name(name: "Rina", meaning: "A pet name for Christina", origin: .english, gender: .female),
    Name(name: "Rita", meaning: "From the name Margarita", origin: .english, gender: .female),
    Name(name: "Robin", meaning: "Feminine of Robert", origin: .english, gender: .female),
    Name(name: "Ronnie", meaning: "From Veronica", origin: .english, gender: .female),
    Name(name: "Rosalind", meaning: "Means tender horse", origin: .english, gender: .female),
    Name(name: "Roseanne", meaning: "Mix between Rose and Ann", origin: .english, gender: .female),
    Name(name: "Rose", meaning: "From the flower", origin: .english, gender: .female),
    Name(name: "Rosemary", meaning: "From the herb", origin: .english, gender: .female),
    Name(name: "Rosie", meaning: "Pet form of Rosemary", origin: .english, gender: .female),
    Name(name: "Rowena", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Roxanne", meaning: "From the name Roxana", origin: .english, gender: .female),
    Name(name: "Ruby", meaning: "From the red gemstone", origin: .english, gender: .female),
    Name(name: "Sabella", meaning: "From the girl’s name Isabella", origin: .english, gender: .female),
    Name(name: "Sabrina", meaning: "From the Celtic legend give name to Severn river", origin: .english, gender: .female),
    Name(name: "Sadie", meaning: "From the name Sarah", origin: .english, gender: .female),
    Name(name: "Sally", meaning: "From the name Sarah", origin: .english, gender: .female),
    Name(name: "Samantha", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Sandra", meaning: "From the name Alessandra", origin: .english, gender: .female),
    Name(name: "Sandy", meaning: "From the name Alexandra", origin: .english, gender: .female),
    Name(name: "Sapphire", meaning: "From the gemstone", origin: .english, gender: .female),
    Name(name: "Scarlett", meaning: "Name based on the colour red", origin: .english, gender: .female),
    Name(name: "Selena", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Shannah", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Shannon", meaning: "From the river in Ireland", origin: .english, gender: .female),
    Name(name: "Sharon", meaning: "From the place in the bible", origin: .english, gender: .female),
    Name(name: "Sheila", meaning: "From the Gaelic name Sile", origin: .english, gender: .female),
    Name(name: "Shirley", meaning: "From a place in England", origin: .english, gender: .female),
    Name(name: "Silver", meaning: "From the metal", origin: .english, gender: .female),
    Name(name: "Sissy", meaning: "From the name Cicely", origin: .english, gender: .female),
    Name(name: "Skye", meaning: "From the English name Sky", origin: .english, gender: .female),
    Name(name: "Sue", meaning: "Pet form of Susan", origin: .english, gender: .female),
    Name(name: "Summer", meaning: "From the season", origin: .english, gender: .female),
    Name(name: "Susan", meaning: "From the name Susanna", origin: .english, gender: .female),
    Name(name: "Sybil", meaning: "From the Greek name Sibylla", origin: .english, gender: .female),
    Name(name: "Sylvia", meaning: "From Silvia", origin: .english, gender: .female),
    Name(name: "Tammy", meaning: "Pet form of Tamara", origin: .english, gender: .female),
    Name(name: "Tamsin", meaning: "Linked to the name Thomas", origin: .english, gender: .female),
    Name(name: "Tansy", meaning: "From the flower", origin: .english, gender: .female),
    Name(name: "Tara", meaning: "This English name means hill", origin: .english, gender: .female),
    Name(name: "Tasha", meaning: "Short for Natasha", origin: .english, gender: .female),
    Name(name: "Tawny", meaning: "From the colour of the owl", origin: .english, gender: .female),
    Name(name: "Teri", meaning: "From the name Terry", origin: .english, gender: .female),
    Name(name: "Tessa", meaning: "From Theresa", origin: .english, gender: .female),
    Name(name: "Thelma", meaning: "Means wish", origin: .english, gender: .female),
    Name(name: "Tiffany", meaning: "Means epiphany", origin: .english, gender: .female),
    Name(name: "Tilda", meaning: "From Matilda", origin: .english, gender: .female),
    Name(name: "Tori", meaning: "From Victoria", origin: .english, gender: .female),
    Name(name: "Tracy", meaning: "From the French place", origin: .english, gender: .female),
    Name(name: "Trina", meaning: "From Katrina", origin: .english, gender: .female),
    Name(name: "Trisha", meaning: "From Patricia", origin: .english, gender: .female),
    Name(name: "Trixie", meaning: "Form of Beatrix", origin: .english, gender: .female),
    Name(name: "Trudy", meaning: "From Gertrude or Ermintrude", origin: .english, gender: .female),
    Name(name: "Unity", meaning: "Manes Unity/Quality", origin: .english, gender: .female),
    Name(name: "Ursa", meaning: "Form of Ursula", origin: .english, gender: .female),
    Name(name: "Ursula", meaning: "From the Latin name Ursula", origin: .english, gender: .female),
    Name(name: "Val", meaning: "Short form of Valerie", origin: .english, gender: .female),
    Name(name: "Valda", meaning: "Inspired by Linda", origin: .english, gender: .female),
    Name(name: "Valene", meaning: "Australian background", origin: .english, gender: .female),
    Name(name: "Valerie", meaning: "Means healthy and strong", origin: .english, gender: .female),
    Name(name: "Vanessa", meaning: "Created by Jonathan Swift", origin: .english, gender: .female),
    Name(name: "Velma", meaning: "Based on Thelma or Selma", origin: .english, gender: .female),
    Name(name: "Vera", meaning: "Has a Russian/Slavic origin", origin: .english, gender: .female),
    Name(name: "Verity", meaning: "Means truth", origin: .english, gender: .female),
    Name(name: "Verona", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Vicky", meaning: "Pet form of Victoria", origin: .english, gender: .female),
    Name(name: "Victoria", meaning: "Means victorious", origin: .english, gender: .female),
    Name(name: "Viola", meaning: "Means violet", origin: .english, gender: .female),
    Name(name: "Violet", meaning: "From the flower", origin: .english, gender: .female),
    Name(name: "Virginia", meaning: "From the name Virgil", origin: .english, gender: .female),
    Name(name: "Vita", meaning: "Pet form of Victoria", origin: .english, gender: .female),
    Name(name: "Vivian", meaning: "Life", origin: .english, gender: .female),
    Name(name: "Wanda", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Wendy", meaning: "Invented in the play Peter Pan", origin: .english, gender: .female),
    Name(name: "Whitney", meaning: "After places in England", origin: .english, gender: .female),
    Name(name: "Willa", meaning: "From the name William", origin: .english, gender: .female),
    Name(name: "Willow", meaning: "From the tree", origin: .english, gender: .female),
    Name(name: "Wilona", meaning: "From Wilma", origin: .english, gender: .female),
    Name(name: "Winifred", meaning: "Joy and Peace", origin: .english, gender: .female),
    Name(name: "Wynne", meaning: "Short form of Winifred", origin: .english, gender: .female),
    Name(name: "Xenia", meaning: "Hospitality and stranger", origin: .english, gender: .female),
    Name(name: "Xenthe", meaning: "Means yellow and bright", origin: .english, gender: .female),
    Name(name: "Yasmin", meaning: "From Jasmin", origin: .english, gender: .female),
    Name(name: "Yolanda", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Zanna", meaning: "From Suzanna", origin: .english, gender: .female),
    Name(name: "Zelda", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Zelene", meaning: "Origin unknown", origin: .english, gender: .female),
    Name(name: "Zera", meaning: "Means Seeds", origin: .english, gender: .female),
    Name(name: "Zoe", meaning: "Means Life", origin: .english, gender: .female),
    
    Name(name: "Roberta", meaning: "This is a meaning for Roberta", origin: .english, gender: .female)
]

var MALE_NAMES: [Name] = [
    Name(name: "Tyler", meaning: "This is a meaning for Tyler", origin: .english, gender: .male),
    
    Name(name: "Aaren", meaning: "the name has several meanings In Scandinavian the meaning of the name Aaren is: Lofty or inspired. it also means high mountain", origin: .english, gender: .male),
    Name(name: "Aaric", meaning: "Rule with Mercy; Graceful Ruler", origin: .english, gender: .male),
    Name(name: "Aaron", meaning: "Messenger (Hebrew); Enlighted; Mountain of Strength; From the Old Testament, Aaron", origin: .english, gender: .male),
    Name(name: "Aart", meaning: "Celtic - Stone; bear; German - Thor; The Eagle ; A variant form of Arthur", origin: .english, gender: .male),
    Name(name: "Aayden", meaning: "someone like fire, fiery", origin: .english, gender: .male),
    Name(name: "Abacuck", meaning: "One who likes to seek adventure and travel", origin: .english, gender: .male),
    Name(name: "Abbe", meaning: "My Father is Joyful ; A Variant of Abby", origin: .english, gender: .male),
    Name(name: "Abbo", meaning: "A Condiment (Mudama Origin)", origin: .english, gender: .male),
    Name(name: "Abell", meaning: "Exhalation of Breath; A Variant of Abel", origin: .english, gender: .male),
    Name(name: "Abhatha", meaning: "A cultural and enthusiastic person", origin: .english, gender: .male),
    Name(name: "Abhigita", meaning: "A happy go lucky and spontaneous person", origin: .english, gender: .male),
    Name(name: "Ablamar", meaning: "A bright, lonely and accepting being", origin: .english, gender: .male),
    Name(name: "Abo", meaning: "Father; Short form of name Abott", origin: .english, gender: .male),
    Name(name: "Abygayle", meaning: "One who is the father of many people", origin: .english, gender: .male),
    Name(name: "Acer", meaning: "means Unity in Latin; A variant of name Ace", origin: .english, gender: .male),
    Name(name: "Achaz", meaning: "Hebrew - God is Holding; One that Takes or Possesses", origin: .english, gender: .male),
    Name(name: "Achestan", meaning: "The stony land bearing oak trees", origin: .english, gender: .male),
    Name(name: "Achim", meaning: "Hebrew - Yahewh will establish; A name variant of Joachim.", origin: .english, gender: .male),
    Name(name: "Achraf", meaning: "Most Honorable One; A variant of Ashraf", origin: .english, gender: .male),
    Name(name: "Ackerleigh", meaning: "Meadow Of Oak Trees; means division of land in English; a variant of Ackerley", origin: .english, gender: .male),
    Name(name: "Ackerley", meaning: "Old English surname meaning Oak meadow.; A variant of Ackley", origin: .english, gender: .male),
    Name(name: "Ackley", meaning: "(English) Meadow of oak trees", origin: .english, gender: .male),
    Name(name: "Acton", meaning: "One who is placed or settled near the oak tree", origin: .english, gender: .male),
    Name(name: "Acwald", meaning: "who is from the forest of oak", origin: .english, gender: .male),
    Name(name: "Acwuld", meaning: "who belongs to the wood of oak", origin: .english, gender: .male),
    Name(name: "Acwulf", meaning: "A wolf from the oak meadows", origin: .english, gender: .male),
    Name(name: "Adair", meaning: "One who is fortunate and powerful", origin: .english, gender: .male),
    Name(name: "Adalson", meaning: "Son of All", origin: .english, gender: .male),
    Name(name: "Adamsson", meaning: "The son of Adam, from earth", origin: .english, gender: .male),
    Name(name: "Adcok", meaning: "The offspring or the son of Adam", origin: .english, gender: .male),
    Name(name: "Addam", meaning: "Son of the Red Earth; A variant of name Adam", origin: .english, gender: .male),
    Name(name: "Addaneye", meaning: "One who is living on a noble person's island", origin: .english, gender: .male),
    Name(name: "Adde", meaning: "Noble; Kind; Wise; Polite", origin: .english, gender: .male),
    Name(name: "Addi", meaning: "A Variant of Adde; Noble; Nobility", origin: .english, gender: .male),
    Name(name: "Addis", meaning: "Son of Adam; Son of the Red Earth; A derivative of name Adam", origin: .english, gender: .male),
    Name(name: "Addney", meaning: "Lives on the Noble's Island; A variant of Adney", origin: .english, gender: .male),
    Name(name: "Adelard", meaning: "noble strength in German; A variant of Abelard", origin: .english, gender: .male),
    Name(name: "Adem", meaning: "Hebrew - Man; Old Greek - Manly; Brave", origin: .english, gender: .male),
    Name(name: "Adey", meaning: "A short form of Adam, of the earth", origin: .english, gender: .male),
    Name(name: "Adgar", meaning: "A happy and peaceful spear", origin: .english, gender: .male),
    Name(name: "Adim", meaning: "In Hebrew - Man; A variant of name Adam", origin: .english, gender: .male),
    Name(name: "Adiran", meaning: "Latin - Man from Hadria; Dark One; A variant form of Adrian", origin: .english, gender: .male),
    Name(name: "Adison", meaning: "A Variant of name Addison, Son of Adam", origin: .english, gender: .male),
    Name(name: "Adisson", meaning: "Son of Adam", origin: .english, gender: .male),
    Name(name: "Adisyn", meaning: "The son or offspring of Adam", origin: .english, gender: .male),
    Name(name: "Adken", meaning: "Oaken; A variant of Adkin which means Man in Hebrew", origin: .english, gender: .male),
    Name(name: "Adkins", meaning: "Son of Aiken; A variant of Adam", origin: .english, gender: .male),
    Name(name: "Adkyn", meaning: "Oaken; A variant of Adkin which means Man in Hebrew", origin: .english, gender: .male),
    Name(name: "Admiral", meaning: "A high rank in the navy", origin: .english, gender: .male),
    Name(name: "Adny", meaning: "Lives on the Noble's Island; A variant of Adney", origin: .english, gender: .male),
    Name(name: "Ado", meaning: "Awe-inspiring; Highborn; Without Further Ceremony; Noble; Nobility", origin: .english, gender: .male),
    Name(name: "Adolfo", meaning: "Noble wolf", origin: .english, gender: .male),
    Name(name: "Adolphus", meaning: "noble wolf; A derivative of name Ado", origin: .english, gender: .male),
    Name(name: "Adras", meaning: "Means Manly in Greek", origin: .english, gender: .male),
    Name(name: "Adred", meaning: "The old counsel, the aged", origin: .english, gender: .male),
    Name(name: "Adstan", meaning: "A noble stone, honourable stone", origin: .english, gender: .male),
    Name(name: "Aeccestane", meaning: "The stone of a swordsman", origin: .english, gender: .male),
    Name(name: "Aecci", meaning: "A cool headed, informal and energetic person", origin: .english, gender: .male),
    Name(name: "Aedan", meaning: "An Irish name which is diminutive form of name Aed implying fire and means born of fire", origin: .english, gender: .male),
    Name(name: "Aedelflete", meaning: "A fast noble person", origin: .english, gender: .male),
    Name(name: "Aednoth", meaning: "A medieval monk, a prelate", origin: .english, gender: .male),
    Name(name: "Aeduin", meaning: "A rich or blessed friend", origin: .english, gender: .male),
    Name(name: "Aeduuard", meaning: "A rich guard of wealth and fortune", origin: .english, gender: .male),
    Name(name: "Aeduuin", meaning: "A blessed friend, a rich one", origin: .english, gender: .male),
    Name(name: "Aefic", meaning: "The King's high reeve", origin: .english, gender: .male),
    Name(name: "Aegheard", meaning: "A protector cowherd", origin: .english, gender: .male),
    Name(name: "Aegthryth", meaning: "The protector of strength", origin: .english, gender: .male),
    Name(name: "Aeker", meaning: "Meadow Of Oak Trees; means division of land in English; a variant of Ackerley", origin: .english, gender: .male),
    Name(name: "Aekerley", meaning: "Meadow Of Oak Trees; means division of land in English; a variant of Ackerley", origin: .english, gender: .male),
    Name(name: "Aekerman", meaning: "Man of Oak; A derivative name from Aeker", origin: .english, gender: .male),
    Name(name: "Aekley", meaning: "Meadow Of Oak Trees; means division of land in English; a variant of Ackerley", origin: .english, gender: .male),
    Name(name: "Aeldredus", meaning: "The noble red-haired person", origin: .english, gender: .male),
    Name(name: "Aelfryth", meaning: "The king of mystical powers", origin: .english, gender: .male),
    Name(name: "Aelfstan", meaning: "A magical stone with supernatural powers", origin: .english, gender: .male),
    Name(name: "Aelfthryth", meaning: "The strength or elf or super powers", origin: .english, gender: .male),
    Name(name: "Aelfwald", meaning: "A forest of supernatural powers", origin: .english, gender: .male),
    Name(name: "Aelfwaru", meaning: "The guard of the mystical powers", origin: .english, gender: .male),
    Name(name: "Aelfweard", meaning: "The guardian of supernatural powers", origin: .english, gender: .male),
    Name(name: "Aelfwin", meaning: "Friend of the mystical powers", origin: .english, gender: .male),
    Name(name: "Aelfwine", meaning: "A friend of elves, or nymphs", origin: .english, gender: .male),
    Name(name: "Aelmer", meaning: "A famous nobleman for his nobility", origin: .english, gender: .male),
    Name(name: "Aelred", meaning: "A noble wise man or counsellor", origin: .english, gender: .male),
    Name(name: "Aembriht", meaning: "A balanced, rational and confident person", origin: .english, gender: .male),
    Name(name: "Aenedleah", meaning: "One who is from an awesome meadows", origin: .english, gender: .male),
    Name(name: "Aenescumb", meaning: "One who lives in the valley of majestic people", origin: .english, gender: .male),
    Name(name: "Aengifu", meaning: "The gift for the eye", origin: .english, gender: .male),
    Name(name: "Aescwig", meaning: "A fight or rumble near the ash tree", origin: .english, gender: .male),
    Name(name: "Aescwine", meaning: "Spear Friend", origin: .english, gender: .male),
    Name(name: "Aescwyn", meaning: "The winner or victor from the ash tree", origin: .english, gender: .male),
    Name(name: "Aesoburne", meaning: "One who is born near the ash tree", origin: .english, gender: .male),
    Name(name: "Aethel", meaning: "A noble snake or one from the Aethelind", origin: .english, gender: .male),
    Name(name: "Aethelard", meaning: "One who descends from the noble snake", origin: .english, gender: .male),
    Name(name: "Aethelbald", meaning: "Noble and Bold; A King of Mercia", origin: .english, gender: .male),
    Name(name: "Aethelbeorht", meaning: "The bright noble snake", origin: .english, gender: .male),
    Name(name: "Aethelbeorn", meaning: "One who is born of a noble snake", origin: .english, gender: .male),
    Name(name: "Aethelberht", meaning: "The bright and shining noble snake", origin: .english, gender: .male),
    Name(name: "Aethelbert", meaning: "Bright Nobility", origin: .english, gender: .male),
    Name(name: "Aethelburh", meaning: "The brightness or a noble snake", origin: .english, gender: .male),
    Name(name: "Aetheldred", meaning: "A noble snake counsellor", origin: .english, gender: .male),
    Name(name: "Aethelfrid", meaning: "The peaceful noble snake", origin: .english, gender: .male),
    
    
    
    
    
]




















